Library Pandas

In [ ]:
#siapkan dataset Iris_raw

In [ ]:
import pandas as pd

In [ ]:
path = '/content/Iris_raw.csv'
df = pd.read_csv(path)

In [ ]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150    4            4.6           3.1            1.5           0.2   
151   17            5.4           3.9            1.3           0.4   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa  
151     Iris-setosa  

[152 rows x 6 columns]

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150    4            4.6           3.1            1.5           0.2   
151   17            5.4           3.9            1.3           0.4   

            Species  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa  
151     Iris-setosa

In [ ]:
len(df)

152

In [ ]:
df.shape

(152, 6)

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  152.000000     149.000000    152.000000     152.000000    152.000000
mean    74.644737       5.836242      3.059868       3.727632      1.186842
std     43.798214       0.834332      0.436157       1.773357      0.765107
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     36.750000       5.100000      2.800000       1.500000      0.300000
50%     74.500000       5.800000      3.000000       4.300000      1.300000
75%    112.250000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df['Species'].describe()

count             152
unique              3
top       Iris-setosa
freq               52
Name: Species, dtype: object

In [ ]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df['SepalLengthCm'].dtypes

dtype('float64')

In [ ]:
df['SepalLengthCm'][100]

nan

In [ ]:
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
147    6.5
148    6.2
149    5.9
150    4.6
151    5.4
Name: SepalLengthCm, Length: 152, dtype: float64

In [ ]:
#iloc

df.iloc[101]

Id                          102
SepalLengthCm               5.8
SepalWidthCm                2.7
PetalLengthCm               5.1
PetalWidthCm                1.9
Species          Iris-virginica
Name: 101, dtype: object

In [ ]:
df.iloc[[101,105,110]]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
101  102            5.8           2.7            5.1           1.9   
105  106            7.6           3.0            6.6           2.1   
110  111            6.5           3.2            5.1           2.0   

            Species  
101  Iris-virginica  
105  Iris-virginica  
110  Iris-virginica

In [ ]:
df.iloc[[101,105,110], 1:3]

SepalLengthCm  SepalWidthCm
101            5.8           2.7
105            7.6           3.0
110            6.5           3.2

In [ ]:
df.iloc[:5, 1:3]

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6

In [ ]:
#loc
df.loc[101]

Id                          102
SepalLengthCm               5.8
SepalWidthCm                2.7
PetalLengthCm               5.1
PetalWidthCm                1.9
Species          Iris-virginica
Name: 101, dtype: object

In [ ]:
df.loc[:5,['SepalLengthCm','SepalWidthCm']]

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
df['Species'].nunique()

3

In [ ]:
df['Species'].count()

152

In [ ]:
df['Species'].value_counts()

Iris-setosa        52
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [ ]:
df['Species'].value_counts(True)  #dalam persentase

Iris-setosa        0.342105
Iris-versicolor    0.328947
Iris-virginica     0.328947
Name: Species, dtype: float64

In [ ]:
df['SepalLengthCm'].value_counts()

5.0    10
5.1     8
6.7     8
6.3     8
5.7     8
6.4     7
5.8     7
5.4     7
5.6     6
5.5     6
6.1     6
6.0     6
4.9     6
4.8     5
6.5     5
4.6     5
6.2     4
7.7     4
6.9     4
5.2     4
5.9     3
4.4     3
6.8     3
7.2     3
6.6     2
4.7     2
7.0     1
5.3     1
4.5     1
4.3     1
7.1     1
7.6     1
7.3     1
7.4     1
7.9     1
Name: SepalLengthCm, dtype: int64

In [ ]:
dfconcat_1 = pd.read_csv('/content/iris_concat_1.csv')
dfconcat_2 = pd.read_csv('/content/iris_concat_2.csv')
dfjoin_1 = pd.read_csv('/content/iris_join_1.csv')
dfjoin_2 = pd.read_csv('/content/iris_join_2.csv')

In [ ]:
dfconcat_1.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
84  85            5.4           3.0            4.5           1.5   
85  86            6.0           3.4            4.5           1.6   
86  87            6.7           3.1            4.7           1.5   
87  88            6.3           2.3            4.4           1.3   
88  89            5.6           3.0            4.1           1.3   

            Species  
84  Iris-versicolor  
85  Iris-versicolor  
86  Iris-versicolor  
87  Iris-versicolor  
88  Iris-versicolor

In [ ]:
dfconcat_2.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0  90            5.5           2.5            4.0           1.3   
1  91            5.5           2.6            4.4           1.2   
2  92            6.1           3.0            4.6           1.4   
3  93            5.8           2.6            4.0           1.2   
4  94            5.0           2.3            3.3           1.0   

           Species  
0  Iris-versicolor  
1  Iris-versicolor  
2  Iris-versicolor  
3  Iris-versicolor  
4  Iris-versicolor

In [ ]:
df = pd.concat([dfconcat_1,dfconcat_2], axis = 0).reset_index()

In [ ]:
df

index   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0        0    1            5.1           3.5            1.4           0.2   
1        1    2            4.9           3.0            1.4           0.2   
2        2    3            4.7           3.2            1.3           0.2   
3        3    4            4.6           3.1            1.5           0.2   
4        4    5            5.0           3.6            1.4           0.2   
..     ...  ...            ...           ...            ...           ...   
147     58  148            6.5           3.0            5.2           2.0   
148     59  149            6.2           3.4            5.4           2.3   
149     60  150            5.9           3.0            5.1           1.8   
150     61  151            4.6           3.1            1.5           0.2   
151     62  152            5.4           3.9            1.3           0.4   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa  
151     Iris-setosa  

[152 rows x 7 columns]

In [ ]:
dfjoin_1.head()

Id  PetalLengthCm  PetalWidthCm      Species
0   1            1.4           0.2  Iris-setosa
1   2            1.4           0.2  Iris-setosa
2   3            1.3           0.2  Iris-setosa
3   4            1.5           0.2  Iris-setosa
4   5            1.4           0.2  Iris-setosa

In [ ]:
dfjoin_2.head()

Id  SepalLengthCm  SepalWidthCm      Species
0   1            5.1           3.5  Iris-setosa
1   2            4.9           3.0  Iris-setosa
2   3            4.7           3.2  Iris-setosa
3   4            4.6           3.1  Iris-setosa
4   5            5.0           3.6  Iris-setosa

In [ ]:
dfjoin_1 = dfjoin_1.set_index('Id')
dfjoin_2 = dfjoin_2.set_index('Id')

In [ ]:
df = dfjoin_1.join(dfjoin_2, how = "inner", lsuffix = '_petal', rsuffix = '_sepal')

In [ ]:
df

PetalLengthCm  PetalWidthCm   Species_petal  SepalLengthCm  SepalWidthCm  \
Id                                                                              
1              1.4           0.2     Iris-setosa            5.1           3.5   
2              1.4           0.2     Iris-setosa            4.9           3.0   
3              1.3           0.2     Iris-setosa            4.7           3.2   
4              1.5           0.2     Iris-setosa            4.6           3.1   
5              1.4           0.2     Iris-setosa            5.0           3.6   
..             ...           ...             ...            ...           ...   
148            5.2           2.0  Iris-virginica            6.5           3.0   
149            5.4           2.3  Iris-virginica            6.2           3.4   
150            5.1           1.8  Iris-virginica            5.9           3.0   
151            1.5           0.2     Iris-setosa            4.6           3.1   
152            1.3           0.4     Iris-setosa            5.4           3.9   

      Species_sepal  
Id                   
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
..              ...  
148  Iris-virginica  
149  Iris-virginica  
150  Iris-virginica  
151     Iris-setosa  
152     Iris-setosa  

[152 rows x 6 columns]

In [ ]:
df = df.drop(['Species_petal'], axis = 1).reset_index()

In [ ]:
df.head()

Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species_sepal
0   1            1.4           0.2            5.1           3.5   Iris-setosa
1   2            1.4           0.2            4.9           3.0   Iris-setosa
2   3            1.3           0.2            4.7           3.2   Iris-setosa
3   4            1.5           0.2            4.6           3.1   Iris-setosa
4   5            1.4           0.2            5.0           3.6   Iris-setosa

In [ ]:
df = df.drop(['Id'], axis = 1)

In [ ]:
df.head()

PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species_sepal
0            1.4           0.2            5.1           3.5   Iris-setosa
1            1.4           0.2            4.9           3.0   Iris-setosa
2            1.3           0.2            4.7           3.2   Iris-setosa
3            1.5           0.2            4.6           3.1   Iris-setosa
4            1.4           0.2            5.0           3.6   Iris-setosa

In [ ]:
df = df.drop(['index'], axis = 1)

KeyError: ignored

In [ ]:
df.head()

PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species_sepal
0            1.4           0.2            5.1           3.5   Iris-setosa
1            1.4           0.2            4.9           3.0   Iris-setosa
2            1.3           0.2            4.7           3.2   Iris-setosa
3            1.5           0.2            4.6           3.1   Iris-setosa
4            1.4           0.2            5.0           3.6   Iris-setosa

In [ ]:
df.shape

(152, 5)

In [ ]:
df.isnull().sum()

PetalLengthCm    0
PetalWidthCm     0
SepalLengthCm    3
SepalWidthCm     0
Species_sepal    0
dtype: int64

In [ ]:
df_new = df

In [ ]:
df_new.dropna().reset_index()

index  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm  \
0        0            1.4           0.2            5.1           3.5   
1        1            1.4           0.2            4.9           3.0   
2        2            1.3           0.2            4.7           3.2   
3        3            1.5           0.2            4.6           3.1   
4        4            1.4           0.2            5.0           3.6   
..     ...            ...           ...            ...           ...   
144    147            5.2           2.0            6.5           3.0   
145    148            5.4           2.3            6.2           3.4   
146    149            5.1           1.8            5.9           3.0   
147    150            1.5           0.2            4.6           3.1   
148    151            1.3           0.4            5.4           3.9   

      Species_sepal  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147     Iris-setosa  
148     Iris-setosa  

[149 rows x 6 columns]

In [ ]:
df_new.shape

(152, 5)

In [ ]:
df_new.isnull().sum()

PetalLengthCm    0
PetalWidthCm     0
SepalLengthCm    3
SepalWidthCm     0
Species_sepal    0
dtype: int64

In [ ]:
df['SepalLengthCm'] = df['SepalLengthCm'].fillna(df['SepalLengthCm'].mean())

In [ ]:
df.isnull().sum()

PetalLengthCm    0
PetalWidthCm     0
SepalLengthCm    0
SepalWidthCm     0
Species_sepal    0
dtype: int64

In [ ]:
df.shape

(152, 5)

In [ ]:
df = df.drop_duplicates().reset_index()

In [ ]:
df.shape

(147, 6)

In [ ]:
df['petal_area'] = 0.5 * df['PetalLengthCm'] * df['PetalWidthCm']

In [ ]:
df.head()

index  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm  \
0      0            1.4           0.2            5.1           3.5   
1      1            1.4           0.2            4.9           3.0   
2      2            1.3           0.2            4.7           3.2   
3      3            1.5           0.2            4.6           3.1   
4      4            1.4           0.2            5.0           3.6   

  Species_sepal  petal_area  
0   Iris-setosa        0.14  
1   Iris-setosa        0.14  
2   Iris-setosa        0.13  
3   Iris-setosa        0.15  
4   Iris-setosa        0.14

In [ ]:
def kategori_luas(luas):
  if luas<2:
    kategori = 'small'
  elif (luas>=2) & (luas<6):
    kategori = 'medium'
  elif luas>6:
    kategori = 'large'
  return kategori

In [ ]:
df['petal_area'] = df['petal_area'].apply(kategori_luas)

In [ ]:
df.head()

index  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm  \
0      0            1.4           0.2            5.1           3.5   
1      1            1.4           0.2            4.9           3.0   
2      2            1.3           0.2            4.7           3.2   
3      3            1.5           0.2            4.6           3.1   
4      4            1.4           0.2            5.0           3.6   

  Species_sepal petal_area  
0   Iris-setosa      small  
1   Iris-setosa      small  
2   Iris-setosa      small  
3   Iris-setosa      small  
4   Iris-setosa      small

In [ ]:
df['petal_area'].value_counts()

medium    74
small     54
large     19
Name: petal_area, dtype: int64

In [ ]:
df = df.rename(columns={'PetalLengthCm':'petal_length', 'PetalWidthCm': 'petal_width', 'SepalWidthCm':'sepal_width', 'SepalLengthCm':'sepal_length','Species_sepal':'species'})

In [ ]:
df.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area is_setosa  species_encode  
0      small    setosa               1  
1      small    setosa               1  
2      small    setosa               1  
3      small    setosa               1  
4      small    setosa               1

In [ ]:
df = df.drop(['index'], axis = 1)

In [ ]:
df.head ()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area  
0      small  
1      small  
2      small  
3      small  
4      small

In [ ]:
df['is_setosa'] = df['species']

In [ ]:
df.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area    is_setosa  
0      small  Iris-setosa  
1      small  Iris-setosa  
2      small  Iris-setosa  
3      small  Iris-setosa  
4      small  Iris-setosa

In [ ]:
df['is_setosa'] = df['is_setosa'].replace({'Iris-setosa': 'setosa', 'Iris-virginica': 'not-setosa', 'Iris-versicolor': 'not-setosa'})

In [ ]:
df.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area is_setosa  
0      small    setosa  
1      small    setosa  
2      small    setosa  
3      small    setosa  
4      small    setosa

In [ ]:
df['is_setosa'].value_counts()

not-setosa    99
setosa        48
Name: is_setosa, dtype: int64

In [ ]:
group = ['petal_length', 'petal_width']
df.groupby(['species','petal_area'])[group].mean()

petal_length  petal_width
species         petal_area                           
Iris-setosa     small           1.462500     0.250000
Iris-versicolor medium          4.379545     1.368182
                small           3.383333     1.016667
Iris-virginica  large           5.952632     2.278947
                medium          5.313333     1.870000

In [ ]:
#mengambil data yang petal area mediaum dan spesiesnya virginica

df_med_vir = df[(df['petal_area']=='medium') & (df['petal_length']>5)]

In [ ]:
df_med_vir.head()

petal_length  petal_width  sepal_length  sepal_width          species  \
81            5.1          1.6           6.0          2.7  Iris-versicolor   
99            5.1          1.9           5.8          2.7   Iris-virginica   
101           5.6          1.8           6.3          2.9   Iris-virginica   
105           6.3          1.8           7.3          2.9   Iris-virginica   
106           5.8          1.8           6.7          2.5   Iris-virginica   

    petal_area   is_setosa  
81      medium  not-setosa  
99      medium  not-setosa  
101     medium  not-setosa  
105     medium  not-setosa  
106     medium  not-setosa

In [ ]:
df_med_vir['petal_area'].unique()

array(['medium'], dtype=object)

In [ ]:
df_med_vir['species'].unique()

array(['Iris-virginica', 'Iris-versicolor'], dtype=object)

In [ ]:
df_med_vir['petal_length'].min()

5.1

In [ ]:
df_med_vir = df_med_vir.sort_values(by='sepal_length', ascending= False).reset_index()

In [ ]:
df_med_vir.head()

index  petal_length  petal_width  sepal_length  sepal_width  \
0    128           6.1          1.9           7.4          2.8   
1    105           6.3          1.8           7.3          2.9   
2    127           5.8          1.6           7.2          3.0   
3    123           6.0          1.8           7.2          3.2   
4    139           5.1          2.3           6.9          3.1   

          species petal_area   is_setosa  
0  Iris-virginica     medium  not-setosa  
1  Iris-virginica     medium  not-setosa  
2  Iris-virginica     medium  not-setosa  
3  Iris-virginica     medium  not-setosa  
4  Iris-virginica     medium  not-setosa

In [ ]:
df_top10 = df_med_vir.head(10)

In [ ]:
df_top10

index  petal_length  petal_width  sepal_length  sepal_width  \
0    128           6.1          1.9           7.4          2.8   
1    105           6.3          1.8           7.3          2.9   
2    127           5.8          1.6           7.2          3.0   
3    123           6.0          1.8           7.2          3.2   
4    139           5.1          2.3           6.9          3.1   
5    137           5.4          2.1           6.9          3.1   
6    110           5.5          2.1           6.8          3.0   
7    142           5.2          2.3           6.7          3.0   
8    122           5.7          2.1           6.7          3.3   
9    106           5.8          1.8           6.7          2.5   

          species petal_area   is_setosa  
0  Iris-virginica     medium  not-setosa  
1  Iris-virginica     medium  not-setosa  
2  Iris-virginica     medium  not-setosa  
3  Iris-virginica     medium  not-setosa  
4  Iris-virginica     medium  not-setosa  
5  Iris-virginica     medium  not-setosa  
6  Iris-virginica     medium  not-setosa  
7  Iris-virginica     medium  not-setosa  
8  Iris-virginica     medium  not-setosa  
9  Iris-virginica     medium  not-setosa

In [ ]:
df.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area is_setosa  
0      small    setosa  
1      small    setosa  
2      small    setosa  
3      small    setosa  
4      small    setosa

In [ ]:
dummies = pd.get_dummies (df['petal_area'], drop_first = True)

In [ ]:
dummies.head()

medium  small
0       0      1
1       0      1
2       0      1
3       0      1
4       0      1

In [ ]:
df_encoding = pd.concat([df,dummies], axis = 1)

In [ ]:
df_encoding = df_encoding.drop(['petal_area'], axis = 1)

In [ ]:
df_encoding.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  is_setosa  medium  small  
0    setosa       0      1  
1    setosa       0      1  
2    setosa       0      1  
3    setosa       0      1  
4    setosa       0      1

In [ ]:
df_corr = df

In [ ]:
df_corr.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  petal_area is_setosa  
0      small    setosa  
1      small    setosa  
2      small    setosa  
3      small    setosa  
4      small    setosa

In [ ]:
df_corr['species_encode'] = df_corr['species'].replace({'Iris-setosa': 1, 'Iris-virginica': 2, 'Iris-versicolor': 3})

In [ ]:
df_corr

petal_length  petal_width  sepal_length  sepal_width         species  \
0             1.4          0.2           5.1          3.5     Iris-setosa   
1             1.4          0.2           4.9          3.0     Iris-setosa   
2             1.3          0.2           4.7          3.2     Iris-setosa   
3             1.5          0.2           4.6          3.1     Iris-setosa   
4             1.4          0.2           5.0          3.6     Iris-setosa   
..            ...          ...           ...          ...             ...   
142           5.2          2.3           6.7          3.0  Iris-virginica   
143           5.0          1.9           6.3          2.5  Iris-virginica   
144           5.2          2.0           6.5          3.0  Iris-virginica   
145           5.4          2.3           6.2          3.4  Iris-virginica   
146           5.1          1.8           5.9          3.0  Iris-virginica   

    petal_area   is_setosa  species_encode  
0        small      setosa               1  
1        small      setosa               1  
2        small      setosa               1  
3        small      setosa               1  
4        small      setosa               1  
..         ...         ...             ...  
142     medium  not-setosa               2  
143     medium  not-setosa               2  
144     medium  not-setosa               2  
145      large  not-setosa               2  
146     medium  not-setosa               2  

[147 rows x 8 columns]

In [ ]:
df_corr = df_corr.corr()

In [ ]:
df_corr

petal_length  petal_width  sepal_length  sepal_width  \
petal_length        1.000000     0.961883      0.858327    -0.421057   
petal_width         0.961883     1.000000      0.803138    -0.356376   
sepal_length        0.858327     0.803138      1.000000    -0.098447   
sepal_width        -0.421057    -0.356376     -0.098447     1.000000   
species_encode      0.642808     0.572391      0.440724    -0.618214   

                species_encode  
petal_length          0.642808  
petal_width           0.572391  
sepal_length          0.440724  
sepal_width          -0.618214  
species_encode        1.000000

Numpy

In [ ]:
import numpy as np

In [ ]:
#array numpy
#bisa memuat vektor maupun matriks

#bedanya dengan list di python basic
#array numpy hanya bisa memuat tipe data numerik (integer dan float)

#bedanya dengan pandas
#pandas series berhubungan dg -> vektor
#pandas dataframe berhubungan dg -> matriks

In [ ]:
mylist = [1,2,3,4,5]
mylist2 = [6,7,8,9,10]

mylist + mylist2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
mylist_array = np.array(mylist)
mylist2_array = np.array(mylist2)

print(mylist_array)
print(mylist2_array)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
mylist_array + mylist2_array

array([ 7,  9, 11, 13, 15])

In [ ]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
mymatrix_array = np.array(mymatrix)
mymatrix_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#arrange

a = np.arange(1,12,2)
#(start, end + 1, selisih)

print(a)

[ 1  3  5  7  9 11]


In [ ]:
tanggal = np.arange(30) + 1

print(tanggal)

#default syntax: selalu start dari 0 dan intervalnya/selisihnya selalu 1

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [ ]:
#zeros and ones

zeros = np.zeros([3,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones([4,4])
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#linspace

b = np.linspace(0,10,3)
#(start, end, banyak/ukuran vektor)

print(b)

[ 0.  5. 10.]


In [ ]:
b = np.arange(0,15,5)
#(start, end, banyak/ukuran vektor)

print(b)

[ 0  5 10]


In [ ]:
#eye
#matriks identitas

eye = np.eye(5)

print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#random
#ada tiga jenis random yang bisa dibuat
#random biasa, random yang mengikuti distribusi normal baku (z), random integer
#random biasa dari (0-1)
#dan random z mempunyai interval dari (-1 sampai 1)

In [ ]:
#random biasa

rand = np.random.rand(3,4)
print(rand)

[[0.30467046 0.42182627 0.95291587 0.54548639]
 [0.41128761 0.49927144 0.5248404  0.16591041]
 [0.51681338 0.10948068 0.83444575 0.44396897]]


In [ ]:
#random mengikuti distribusi normal baku (z)

randn = np.random.randn(3,4)
print(randn)

[[-0.9893613   1.77544773  0.84000143  0.38588813]
 [ 0.05097192 -0.14721646 -0.08869701 -1.33738447]
 [-0.43323433  2.01694832  0.62608611  0.69235665]]


In [ ]:
#random integer

randi = np.random.randint(1,100,[3,4])
#(batas bawah, batas atas, [ukuran matriks])

print(randi)

[[14 70 36 12]
 [63 73 37 57]
 [51 34  8 77]]


In [ ]:
randi.shape

(3, 4)

In [ ]:
randi.dtype

dtype('int64')

Ploty Library untuk Visualisasi Data

In [ ]:
import plotly.express as px

In [ ]:
#Line chart
#baik digunakan untuk plot data yang sumbu x nya waktu
#contoh dari sumber lain
print(tanggal)
y_data = np.random.randint(10,20,30)
#buat array dengan angka random antara 10 sampai 20, sebanyak 30 buah
print(y_data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[15 19 16 14 15 17 13 18 18 18 17 12 16 19 11 16 18 12 10 16 10 13 11 19
 12 17 19 13 19 19]


In [ ]:
fig_line = px.line(x = tanggal, y = y_data, title = 'Penjualan Harian')
fig_line.update_yaxes(title = 'Banyak Sales')
fig_line.update_xaxes(title = 'Tanggal')
fig_line.show()

In [ ]:
#bar chart
#salah satu sumbunya kategorikal
#sumbu lainnya numerik

df_bar = df.groupby(['species'], as_index = False)['petal_length'].mean()
df_bar

species  petal_length
0      Iris-setosa      1.462500
1  Iris-versicolor      4.260000
2   Iris-virginica      5.561224

In [ ]:
fig_bar = px.bar(df_bar, x = 'species', y = 'petal_length', title = 'Rataan Panjang Petal')
fig_line.update_yaxes(title = 'Rata-rata Panjang Petal')
fig_line.update_xaxes(title = 'species')
fig_bar.show()

In [ ]:
fig_bar = px.bar(df_bar, x = 'petal_length', y = 'species', title = 'Rataan Panjang Petal')
fig_line.update_xaxes(title = 'Rata-rata Panjang Petal')
fig_line.update_yaxes(title = 'species')
fig_bar.show()

In [ ]:
df_bar2 = df.groupby(['petal_area','is_setosa'], as_index = False).count()
df_bar2

petal_area   is_setosa  petal_length  petal_width  sepal_length  \
0      large  not-setosa            19           19            19   
1     medium  not-setosa            74           74            74   
2      small  not-setosa             6            6             6   
3      small      setosa            48           48            48   

   sepal_width  species  species_encode  
0           19       19              19  
1           74       74              74  
2            6        6               6  
3           48       48              48

In [ ]:
fig_bar2 = px.bar(df_bar2, x = 'is_setosa', y = 'petal_length',
                  color= 'petal_area', title = 'Luas Petal Iris',
                  orientation = 'v', barmode = 'group')
#barmode = 'overlay', barmode = 'stack'
#fig_bar2 = px.bar(df_bar2, x = 'is_setosa', y = 'petal_length', title = 'Luas Petal Iris')
fig_bar2.show()

In [ ]:
#histogram
#di sumbu y nya menampilkan frekuensi
#melihat sebaran data, distribusi data, cocok digunakan untuk data numerik

fig_hist = px.histogram(df, x = 'sepal_width',
                        color = 'is_setosa', opacity = 0.5, barmode = 'overlay',
                        title = 'Sebaran Lebar Sepal',
                        histnorm = 'percent', text_auto = True)
fig_hist.show()

In [ ]:
#scatter plot
#saat ingin membuat visualisasi yang kedua sumbunya merupakan data numerik

fig_sctatter = px.scatter(df, x = 'sepal_length', y = 'sepal_width', title = ' Panjang vs Lebar Sepal',
                          size = 'petal_length', color = 'species')
fig_sctatter.show()

In [ ]:
#pie chart
#mirip penggunaan barchart
#ketika memiliki banyak (>5) kategori sebaiknya jangan pakai pie chart

df_pie = df.groupby(['species'])['petal_length'].count()
df_pie

species
Iris-setosa        48
Iris-versicolor    50
Iris-virginica     49
Name: petal_length, dtype: int64

In [ ]:
fig_pie = px.pie(df_pie, values = df_pie.values, names = df_pie.index)
fig_pie.show()

In [ ]:
#boxplot
#data yg diplotnya: 1 kolom kategorikal, 1 kolom numerik
#mau melihat sebaran data (secara tujuan mirip histogram)

fig_box = px.box(df, x = 'species', y = 'sepal_length', title = 'Sebaran Panjang Sepal')
fig_box.show()

In [ ]:
#plot korelasi
fig_corr = px.imshow(df_corr, text_auto = True, width = 1000,
                     height = 600, aspect = 'auto')
fig_corr.show()

In [ ]:
df_corr

petal_length  petal_width  sepal_length  sepal_width  \
petal_length        1.000000     0.961883      0.858327    -0.421057   
petal_width         0.961883     1.000000      0.803138    -0.356376   
sepal_length        0.858327     0.803138      1.000000    -0.098447   
sepal_width        -0.421057    -0.356376     -0.098447     1.000000   
species_encode      0.642808     0.572391      0.440724    -0.618214   

                species_encode  
petal_length          0.642808  
petal_width           0.572391  
sepal_length          0.440724  
sepal_width          -0.618214  
species_encode        1.000000

Sklearn

In [ ]:
#regresi linear
#supervised learning - regresi

y = df_encoding['petal_width']
x = df_encoding.drop(['species', 'is_setosa', 'medium',
                      'small', 'petal_width'], axis = 1)

In [ ]:
y.head()

0    0.2
1    0.2
2    0.2
3    0.2
4    0.2
Name: petal_width, dtype: float64

In [ ]:
x.head()

petal_length  sepal_length  sepal_width
0           1.4           5.1          3.5
1           1.4           4.9          3.0
2           1.3           4.7          3.2
3           1.5           4.6          3.1
4           1.4           5.0          3.6

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 101)

In [ ]:
#import modul
from sklearn.linear_model import LinearRegression

In [ ]:
#create model
linear_model = LinearRegression()

In [ ]:
#data training/data fitting
linear_model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_predict = linear_model.predict(x_test)

In [ ]:
from sklearn import metrics

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, y_predict))
print('MSE:', metrics.mean_squared_error(y_test, y_predict))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))

MAE: 0.15076060943264522
MSE: 0.03992004899222304
RMSE: 0.1998000225030594


In [ ]:
#klasifikasi
df_encoding.head()

petal_length  petal_width  sepal_length  sepal_width      species  \
0           1.4          0.2           5.1          3.5  Iris-setosa   
1           1.4          0.2           4.9          3.0  Iris-setosa   
2           1.3          0.2           4.7          3.2  Iris-setosa   
3           1.5          0.2           4.6          3.1  Iris-setosa   
4           1.4          0.2           5.0          3.6  Iris-setosa   

  is_setosa  medium  small  
0    setosa       0      1  
1    setosa       0      1  
2    setosa       0      1  
3    setosa       0      1  
4    setosa       0      1

In [ ]:
y = df_encoding['is_setosa']
x = df_encoding.drop(['species', 'is_setosa'], axis=1)

In [ ]:
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: is_setosa, dtype: object

In [ ]:
x.head()

petal_length  petal_width  sepal_length  sepal_width  medium  small
0           1.4          0.2           5.1          3.5       0      1
1           1.4          0.2           4.9          3.0       0      1
2           1.3          0.2           4.7          3.2       0      1
3           1.5          0.2           4.6          3.1       0      1
4           1.4          0.2           5.0          3.6       0      1

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 101)

In [ ]:
#regresi logistik
#import modul

from sklearn.linear_model import LogisticRegression

In [ ]:
#create model
logmodel = LogisticRegression()

In [ ]:
#fitting data
logmodel.fit(x_train, y_train)
LogisticRegression()

LogisticRegression()

In [ ]:
#prediksi oleh model
y_predict =logmodel.predict(x_test)

In [ ]:
y_predict

array(['not-setosa', 'not-setosa', 'setosa', 'not-setosa', 'setosa',
       'not-setosa', 'not-setosa', 'not-setosa', 'setosa', 'not-setosa',
       'not-setosa', 'not-setosa', 'not-setosa', 'not-setosa', 'setosa',
       'not-setosa', 'setosa', 'not-setosa', 'not-setosa', 'not-setosa',
       'not-setosa', 'not-setosa', 'setosa', 'not-setosa', 'setosa',
       'not-setosa', 'setosa', 'not-setosa', 'not-setosa', 'not-setosa'],
      dtype=object)

In [ ]:
y_test

66     not-setosa
122    not-setosa
16         setosa
78     not-setosa
32         setosa
64     not-setosa
118    not-setosa
109    not-setosa
25         setosa
143    not-setosa
91     not-setosa
92     not-setosa
106    not-setosa
77     not-setosa
1          setosa
93     not-setosa
43         setosa
53     not-setosa
125    not-setosa
97     not-setosa
98     not-setosa
139    not-setosa
41         setosa
86     not-setosa
33         setosa
100    not-setosa
31         setosa
61     not-setosa
131    not-setosa
80     not-setosa
Name: is_setosa, dtype: object

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

  not-setosa       1.00      1.00      1.00        22
      setosa       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[22  0]
 [ 0  8]]


In [ ]:
y_predict_proba = logmodel.predict_proba(x_test)

In [ ]:
y_predict_proba

array([[9.96956023e-01, 3.04397673e-03],
       [9.99675658e-01, 3.24341646e-04],
       [1.44637122e-02, 9.85536288e-01],
       [9.72869101e-01, 2.71308994e-02],
       [1.31219364e-02, 9.86878064e-01],
       [9.92605425e-01, 7.39457512e-03],
       [9.99665711e-01, 3.34288601e-04],
       [9.99411351e-01, 5.88648704e-04],
       [4.06184470e-02, 9.59381553e-01],
       [9.99047992e-01, 9.52008496e-04],
       [8.37069831e-01, 1.62930169e-01],
       [9.87381362e-01, 1.26186385e-02],
       [9.99824849e-01, 1.75150692e-04],
       [8.84932710e-01, 1.15067290e-01],
       [2.63942424e-02, 9.73605758e-01],
       [9.82892714e-01, 1.71072861e-02],
       [2.78197550e-02, 9.72180245e-01],
       [9.92796291e-01, 7.20370907e-03],
       [9.97904377e-01, 2.09562289e-03],
       [9.83779933e-01, 1.62200672e-02],
       [9.99760358e-01, 2.39642045e-04],
       [9.99270090e-01, 7.29910192e-04],
       [3.80932392e-02, 9.61906761e-01],
       [9.80157110e-01, 1.98428899e-02],
       [1.344439

In [ ]:
y_predict

array(['not-setosa', 'not-setosa', 'setosa', 'not-setosa', 'setosa',
       'not-setosa', 'not-setosa', 'not-setosa', 'setosa', 'not-setosa',
       'not-setosa', 'not-setosa', 'not-setosa', 'not-setosa', 'setosa',
       'not-setosa', 'setosa', 'not-setosa', 'not-setosa', 'not-setosa',
       'not-setosa', 'not-setosa', 'setosa', 'not-setosa', 'setosa',
       'not-setosa', 'setosa', 'not-setosa', 'not-setosa', 'not-setosa'],
      dtype=object)